export const ACTIVITY_TYPE = {
    gc_order_accepted: { name: 'Green coffee order accepted' },
    gc_order_rejected: { name: 'Green coffee order rejected' },
    new_gc_order_created: { name: 'New green coffee order placed' },
    gc_order_updated: { name: 'Order updated' },
    review_added_for_facilitator: { name: 'Review added for a service' },
    deleted_facilitator_review: { name: 'Deleted review for a service' },
    review_added_for_estate: { name: 'Review added for the estate' },
    deleted_estate_review: { name: 'Deleted review for a service' },
    review_added_for_roaster: { name: 'Deleted review for an estate' },
    deleted_roaster_review: { name: 'Deleted review for a roaster' },
    review_added_for_micro_roaster: { name: 'Review added for a micro-roaster' },
    deleted_micro_roaster_review: { name: 'Deleted review for a micro-roaster' },
    new_rc_batch_added: { name: 'New roasted coffee batch added' },
    updated_rc_batch: { name: 'Roasted coffee batch updated' },
    deleted_rc_batch: { name: 'Roaster coffee batch deleted' },
    new_certificate_added: { name: 'New certificate added' },
    certificate_updated: { name: 'Certificate updated' },
    certificatre_deleted: { name: 'Certificate deleted' },
    updated_roaster_profile: { name: 'Roaster profile updated' },
    new_hrc_token_generated: { name: 'New partner token generated' },
    new_mr_token_generated: { name: 'New Micro-Roaster token generated' },
    new_roasting_profie_added: { name: 'New roasting profile added' },
    roasting_profile_updated: { name: 'New roasting profile updated' },
    roasting_profile_deleted: { name: 'New roasting profile deleted' },
    new_role_added: { name: 'New role added' },
    role_deleted: { name: 'Role deleted' },
    role_updated: { name: 'Role updated' },
    assigned_permission: { name: 'Assigned permission' },
    new_user_certificate_added: { name: 'New user certificate added' },
    user_certificate_updated: { name: 'User certificate updated' },
    user_certificate_deleted: { name: 'User certificate deleted' },
    ro_profile_updated: { name: 'Roaster profile updated' },
    ro_profile_added: { name: 'Roaster profile added' },
    new_address_added: { name: 'New address added' },
    address_updated: { name: 'Address updated' },
    address_deleted: { name: 'Address deleted' },
    new_ro_brand_created: { name: 'New roastery brand created' },
    ro_brand_updated: { name: 'Roastery brand updated' },
    ro_brand_deleted: { name: 'Roastery brand deleted' },
    new_ro_agreement_added: { name: 'New sales contract added' },
    new_ro_agreement_updated: { name: 'New sales contract updated' },
    new_ro_agreement_deleted: { name: 'New sales contract deleted' },
    new_green_coffee_order_created: { name: 'New green coffee order placed' },
    new_sample_request_added: { name: 'New order for sample request raised' },
    green_coffee_order_cancelled: { name: 'Order cancelled' },
    green_coffee_order_payment_receipt_updated: { name: 'Order payment updated' },
    green_coffee_order_updated: { name: 'Order updated' },
    new_dispute_created: { name: 'New dispute created' },
    dispute_resolved: { name: 'Dispute resolved' },
    dispute_escalated: { name: 'Dispute escalated' },
    dispute_assigned: { name: 'Dispute assigned' },
    new_dispute_attachment_added: { name: 'Dispute attachment added' },
    deleted_micro_roaster_profile: { name: 'Micro roaster profile deleted' },
    updated_micro_roaster_profile: { name: 'Micro roaster profile updated' },
    new_ecommerce_product_added: { name: 'New e-comm product added' },
    ecommerce_product_updated: { name: 'E-comm product updated' },
    ecommerce_product_deleted: { name: 'E-comm product deleted' },
    ecommerce_product_weight_variant_added: { name: 'E-comm product weight variant added' },
    ecommerce_product_weight_variant_updated: { name: 'E-comm product weight variant updated' },
    ecommerce_product_weight_variant_deleted: { name: 'E-comm product weight variant deleted' },
    estate_details_updated: { name: 'Estate details updated' },
    new_faq_added: { name: 'New FAQ added' },
    faq_updated: { name: 'FAQ updated' },
    faq_deleted: { name: 'FAQ deleted' },
    new_contact_addded: { name: 'New contact added' },
    contact_deleted: { name: 'Contact deleted' },
    default_coffee_experience_updated: { name: 'Default coffee experience updated' },
    coffee_experience_updated: { name: 'Coffee experience updated' },
    green_coffee_order_payment_receipt_verified: { name: 'Order payment receipt verified' },
    green_coffee_order_shipment_details_added: { name: 'Order shipment details added' },
    green_coffee_order_marked_as_received: { name: 'Order marked as recieved' },
    mr_profile_updated: { name: 'Micro roaster profile updated' },
    user_profile_status_updated: { name: 'User profile status updated' },
    role_assigned: { name: 'Role assigned' },
    user_role_deleted: { name: 'User role deleted' },
    user_preferences_updated: { name: 'Preferences updated' },
    green_coffee_order_user_assigned: { name: 'User assigned to order' },
    default_facilitator_added: { name: 'Default facilitator added' },
    default_facilitator_updated: { name: 'Default facilitator updated' },
    es_visiblity_enabled: { name: 'Estate visibility enabled' },
    es_visiblity_disabled: { name: 'Estate visibility disabled' },
    vat_setting_updated: { name: 'VAT setting updated' },
    vat_setting_added: { name: 'VAT settings added' },
    vat_setting_deleted: { name: 'VAT settings deleted' },
    ro_lot_pre_booked: { name: 'Land lot pre-booked' },
    gc_order_cancelled: { name: 'Order cancelled' },
    hrc_onboarded: { name: 'Partner onboarded' },
    hrc_partner_updated: { name: 'Partner updated' },
    hrc_status_updated: { name: 'Partner status updated' },
    hrc_discount_updated: { name: 'Partner discount updated' },
    hrc_updated: { name: 'Partner updated' },
    mr_updated: { name: 'Micro roaster updated' },
    hrc_role_updated: { name: 'Role updated' },
    hrc_role_created: { name: 'Role created' },
    hrc_role_deleted: { name: 'Role deleted' },
    hrc_role_assigned: { name: 'Role assigned' },
    hrc_review_added: { name: 'Partner review added' },
    hrc_review_deleted: { name: 'Partner review deleted' },
    roaster_onboarded: { name: 'Roaster onboarded' },
    es_company_slug_added: { name: 'Estate company slug added' },
    ro_company_slug_added: { name: 'Roaster company slug added' },
    ro_order_reference_added: { name: 'Roaster reference number added' },
    hrc_outlet_address_updated: { name: 'Outlet address updated' },
    hrc_outlet_timing_updated: { name: 'Outlet timing updated' },
    hrc_outlet_menu_images_updated: { name: 'Outlet menu images updated' },
    hrc_outlet_stories_added: { name: 'Outlest stories added' },
    hrc_outlet_stories_removed: { name: 'Outlet stories removed' },
    es_variety_added: { name: 'Variety added' },
    es_variety_edited: { name: 'Variety edited' },
    es_variety_deleted: { name: 'Variety deleted' },
    ro_role_users_assigned: { name: 'User assigned to a role' },
    es_role_users_assigned: { name: 'User assigned to a role' },
    mr_role_users_assigned: { name: 'User assigned to a role' },
    hrc_role_users_assigned: { name: 'User assigned to a role' },
    recipe_posted: { name: 'Recipe posted in the coffee lab' },
    recipe_updated: { name: 'Recipe updated in the coffee lab' },
    recipe_deleted: { name: 'Recipe deleted in the coffee lab' },
    comment_posted: { name: 'Comment posted in the coffee lab' },
    comment_updated: { name: 'Comment updated in the coffee lab' },
    comment_deleted: { name: 'Comment deleted in the coffee lab' },
    notification_all_read: { name: 'Notificates marked as read' },
    es_user_preferences_updated: { name: 'User preferences updated' },
    mr_user_preferences_updated: { name: 'User preferences updated' },
    ro_user_preferences_updated: { name: 'User preferences updated' },
    es_banner_deleted: { name: 'Banner deleted' },
    ro_banner_deleted: { name: 'Banner deleted' },
    fc_banner_deleted: { name: 'Banner deleted' },
    mr_banner_deleted: { name: 'Banner deleted' },
    hrc_banner_deleted: { name: 'Banner deleted' },
    outtake_order_created: { name: 'Outtake order created' },
    outtake_order_updated: { name: 'Outtake orderupdated' },
    co_review_added: { name: 'Code of conduct audit review added' },
    co_review_deleted: { name: 'Code of conduct audit review updated' },

    new_fc_address_added: { name: 'New address added' },
    fc_address_updated: { name: 'Address updated' },
    fc_address_deleted: { name: 'Address deleted' },
    fc_estate_profile_created: { name: 'Estate profile created' },
    fc_contract_status_updated: { name: 'Contract status updated' },
    fc_contract_new_file_attached: { name: 'New contract fiel added' },
    fc_contract_file_deleted: { name: 'Contract file deleted' },
    fc_dry_milling_request_updated: { name: 'Dry milling request updated' },
    fc_wet_milling_request_updated: { name: 'Wet milling request updated' },
    fc_import_delivery_request_updated: { name: 'Import & delivery request updated' },
    fc_import_delivery_request_attachment_added: { name: 'Attachment added in Import & delivery request' },
    fc_export_service_document_added: { name: 'Attachment added in export request' },
    fc_export_service_shipping_info_added: { name: 'Shipping info addded in export request' },
    fc_export_service_details_added: { name: 'Export service details added' },
    fc_new_lot_created: { name: 'New land lot created' },
    lot_deleted_by_fc: { name: 'Land lot deleted by Operator' },
    lot_updated_by_fc: { name: 'Land lot updated by Operator' },
    profile_image_uploaded: { name: 'Profile image uploaded' },
    profile_image_deleted: { name: 'Profile image deleted' },
    fc_user_preferences_updated: { name: 'User preferences updated' },
    file_uploaded: { name: 'File uploaded' },
    file_updated: { name: 'File updated' },
    file_moved: { name: 'File moved' },
    file_shared: { name: 'File shared' },
    file_attached: { name: 'File attached' },
    file_permission_updated: { name: 'File permission updated' },
    file_share_revoked: { name: 'File shre revoked' },
    fc_cupping_report_added: { name: 'Cupping report added' },
    ro_cupping_report_added: { name: 'Cupping report added' },
    mr_cupping_report_added: { name: 'Cupping report added' },
    hrc_cupping_report_added: { name: 'Cupping report added' },
    fc_cupping_external_report_added: { name: 'Cupping invited evaluator report added' },
    ro_cupping_external_report_added: { name: 'Cupping invited evaluator report added' },
    mr_cupping_external_report_added: { name: 'Cupping invited evaluator report added' },
    hrc_cupping_external_report_added: { name: 'Cupping invited evaluator report added' },
    fc_cupping_report_status_updated: { name: 'Cupping report status updated' },
    ro_cupping_report_status_updated: { name: 'Cupping report status updated' },
    mr_cupping_report_status_updated: { name: 'Cupping report status updated' },
    hrc_cupping_report_status_updated: { name: 'Cupping report status updated' },
    fc_cupping_report_type_updated: { name: 'Cupping report type updated' },
    ro_cupping_report_type_updated: { name: 'Cupping report type updated' },
    mr_cupping_report_type_updated: { name: 'Cupping report type updated' },
    hrc_cupping_report_type_updated: { name: 'Cupping report type updated' },
    fc_sample_shipping_details_added: { name: 'Sample shipment delivery details added' },
    fc_sample_pickup_details_added: { name: 'Sample pickup details added' },
    fc_code_of_conduct_added: { name: 'Code of conduct report added' },
    fc_service_added: { name: 'New service added' },
    fc_service_updated: { name: 'Service updated' },
    fc_service_deleted: { name: 'Service deleted' },
    fc_estate_onboard: { name: 'Estate onboarded' },
    fc_user_profile_updated: { name: 'User profile updated' },
    sa_user_profile_deleted: { name: 'User profile deleted' },
    fc_user_profile_deleted: { name: 'User profile deleted' },
    es_user_profile_deleted: { name: 'User profile deleted' },
    ro_user_profile_deleted: { name: 'User profile deleted' },
    mr_user_profile_deleted: { name: 'User profile deleted' },
    hrc_user_profile_deleted: { name: 'User profile deleted' },
    fc_settings_updated: { name: 'Settings updated' },
    fc_role_created: { name: 'Role created' },
    fc_role_updated: { name: 'Role updated' },
    fc_role_deleted: { name: 'Role deleted' },
    fc_role_assigned: { name: 'Role assigned' },
    new_fc_service_request: { name: 'New service request receieved' },
    user_assigned_to_fc_service_request: { name: 'User assigned to a service request' },
    fc_service_request_completed: { name: 'Service request completed' },
    fc_service_request_rejected: { name: 'Service request rejected' },
    fc_service_request_status_changed: { name: 'Service request status changed' },
    request_to_change_fc_service_request_assignee: { name: 'Request to change service assignee' },
    simulated_login_enabled: { name: 'Simulated login enabled' },
    simulated_login_disabled: { name: 'Simulated login disabled' },
    service_image_uploaded: { name: 'Service image uploaded' },
    service_image_deleted: { name: 'Service image deleted' },
    fc_user_onboarded: { name: 'User onboarded' },
    fc_role_users_assigned: { name: 'Role assigned' },

    hrc_on: { name: '"Name":"Partner onboarded' },
    hrc_order_created: { name: 'Order created' },
    hrc_order_shipment_updated: { name: 'Order shipment updated' },
    hrc_order_payment_status_updated: { name: 'Payment status of order updated' },
    hrc_order_status_updated: { name: 'Order status updated' },
    hrc_address_added: { name: 'Address added' },
    hrc_address_updated: { name: 'Address updated' },
    hrc_address_deleted: { name: 'Address deleted' },
    hrc_invite_token_updated: { name: 'Invite token updated' },
    hrc_user_preferences_updated: { name: 'Preference updated' },

    sa_profile_updated: { name: 'Profile updated' },
    sa_role_created: { name: 'Role created' },
    sa_role_updated: { name: 'Role updated' },
    sa_role_deleted: { name: 'Role deleted' },
    sa_role_assigned: { name: 'Role assigned' },
    sa_user_role_deleted: { name: 'User role deleted' },
    sa_roaster: { name: 'Roaster' },
    roaster_deleted: { name: 'Roaster deleted' },
    roaster_status_updated: { name: 'Roaster status updated' },
    sa_setting_updated: { name: 'Setting updated' },
    sa_commission_setting_updated: { name: 'Commission setting updated' },
    sa_billing_details_updated: { name: 'Billing details updated' },
    sa_terms_and_conditions_updated: { name: 'Terms & conditions updated' },
    sa_privacy_policy_updated: { name: 'Privacy policy updated' },
    sa_email_template_created: { name: 'Email template created' },
    sa_email_template_updated: { name: 'Email template updated' },
    sa_email_template_deleted: { name: 'Email template deleted' },
    sa_question_added: { name: 'Question added in the coffee lab' },
    sa_question_assigned: { name: 'Question assigned in the coffee lab' },
    answer_added: { name: 'Answer added in the coffee lab' },
    lead_updated: { name: 'Lead generated list updated' },
    sa_role_users_assigned: { name: 'Users assigned to the role' },
    sa_user_preferences_updated: { name: 'Perferences update' },

    ro_mr_public_onboard_approved: { name: 'Micro roaster onboarding approved' },
};
