export const ACTIVITY_TYPE = {
    hrc_role_assigned: {
        name: 'Horeca Role Assigned',
    },
    hrc_updated: {
        name: 'Horeca Updated',
    },
    vat_setting_updated: {
        name: 'Vat Setting Updated',
    },
    default_coffee_experience_updated: {
        name: 'Default coffee experience is Updated',
    },
    rc_batch: { name: '' },
    certificate: { name: '' },
    profile: { name: '' },
    hrc_token: { name: '' },
    mc_token: { name: '' },
    ro_roasting_profile: { name: '' },
    role: { name: '' },
    permission: { name: '' },
    user_certificate: { name: '' },
    ro_address: { name: '' },
    ro_brand: { name: '' },
    ro_agreement: { name: '' },
    gc_order: { name: '' },
    sample_request: { name: '' },
    dispute: { name: '' },
    micro_roaster: { name: '' },
    ecommerce_product: { name: '' },
    contacts: { name: '' },
    file_manager: { name: '' },
    user_preference: { name: '' },
    fc_review: { name: '' },
    es_review: { name: '' },
    ro_review: { name: '' },
    mr_review: { name: '' },
    preferences: { name: '' },
    coffee_experience: { name: '' },
    mr_gc_order: { name: '' },
    company_certificate: { name: '' },
    default_facilitator: { name: '' },
    es_visibility: { name: '' },
    hrc_onboard: { name: '' },
    hrc_partner: { name: '' },
    hrc_status: { name: '' },
    hrc_discount: { name: '' },
    hrc_update: { name: '' },
    mr_update: { name: '' },
    hrc_role: { name: '' },
    hrc_review: { name: '' },
    co_review: { name: '' },
    vat_setting: { name: '' },
    company_slug: { name: '' },
    hrc_outlet: { name: '' },
    es_variety: { name: '' },
    recipes: { name: '' },
    notification: { name: '' },
    comment: { name: '' },
    profile_banner: { name: '' },
    outtake_order: { name: '' },
    fc_cupping_service: { name: '' },
    ro_cupping_service: { name: '' },
    mr_cupping_service: { name: '' },
    hrc_cupping_service: { name: '' },
    code_of_conduct: { name: '' },
    fc_onboard: { name: '' },
    sa_user_profile: { name: '' },
    fc_user_profile: { name: '' },
    es_user_profile: { name: '' },
    ro_user_profile: { name: '' },
    mr_user_profile: { name: '' },
    hrc_user_profile: { name: '' },
    fc_settings: { name: '' },
    fc_role: { name: '' },
    fc_service: { name: '' },
    fc_address: { name: '' },
    estate: { name: '' },
    estate_user_profile: { name: '' },
    fc_contract: { name: '' },
    faq: { name: '' },
    milling: { name: '' },
    import_delivery_service: { name: '' },
    fc_export_service: { name: '' },
    lot: { name: '' },
    profile_image: { name: '' },
    sample_shipping: { name: '' },
    branding_estates_service: { name: '' },
    service_image: { name: '' },
    ecom_order: { name: '' },
    hrc_address: { name: '' },
    hrc_invite_token: { name: '' },
    sa_profile: { name: '' },
    sa_role: { name: '' },
    sa_settings: { name: '' },
    sa_commission_setting: { name: '' },
    sa_email_template: { name: '' },
    sa_questions: { name: '' },
    answers: { name: '' },
    lead: { name: '' },
    roaster: { name: '' },
};
