export const environment = {
    apiURL: 'https://fed-api.sewnstaging.com',
    wsEndpoint: 'wss://messaging.sewnstaging.com/v1',
    chatUploadEndPoint: 'https://messaging.sewnstaging.com/v1/',
    ssoWeb: 'http://localhost:4300',
    estatesWeb: 'http://localhost:4200',
    facilitatorWeb: 'http://localhost:4201',
    roasterWeb: 'http://localhost:4202',
    microRoasterWeb: 'http://localhost:4203',
    horecaWeb: 'http://localhost:4204',
    adminWeb: 'http://localhost:4205',
    consumerWeb: 'http://localhost:4206',
    agroUrl: 'https://api.agromonitoring.com/agro/1.0/',
    estateBrandProfileUrl: 'http://localhost:4207/estate',
    roasterBrandProfileUrl: 'http://localhost:4208/roaster',
    termsUserUrl: 'https://support.eraofwe.com/en/kb/articles/general-terms-conditions-user',
    termsEntityUrl: 'https://support.eraofwe.com/en/kb/articles/general-terms-conditions-legal-entity',
    privacyPolicyUrl: 'https://support.eraofwe.com/en/kb/articles/privacy-policy',
    cookiePolicyUrl: 'https://support.eraofwe.com/en/kb/articles/cookie-policy',
    encryptionKey: 'sewen_secrete_key',
    googleTranslationAPIKey: 'AIzaSyBEDVxvYT9-dlcBz83jitndZ4xODAJiqO0',
    supportEmailAddress: 'support@eraofwe.com',
    shopWeb: 'https://sewnstagingshop.com/shop',
    production: false,
};
