export enum MessageMetaTypes {
    TEXT_ONLY = 'TEXT_ONLY',
    DISPUTE_RAISED = 'DISPUTE_RAISED',
    STICKER = 'STICKER',
    PICTURE_CAPTION = 'PICTURE_CAPTION',
    PICTURE_ONLY = 'PICTURE_ONLY',
}
