export enum SocketMessageOrigin {
    DIRECT_MESSAGING = 'DIRECT_MESSAGING',
    ORDER_CHAT = 'ORDER_CHAT',
    SERVICE_CHAT = 'SERVICE_CHAT',
    UTIL_ONLINE = 'UTIL_ONLINE',
    UTIL_AUTH = 'UTIL_AUTH',
}
