export const VALIDATION_LIST: any = {
    required: 've_required',
    ve_too_long: 'too_long',
    too_short: 've_too_short',
    different_length: 've_different_length',
    too_large: 've_too_large',
    too_small: 've_too_small',
    out_of_range: 've_out_of_range',
    not_alpha: 've_not_alpha',
    not_numeric: 've_not_numeric',
    not_alpha_numeric: 've_not_alpha_numeric',
    invalid: 've_invalid',
    already_exists: 've_already_exists',
    do_not_match: 've_do_not_match',
    not_found: 've_not_found',
    cannot_change: 've_cannot_change',
    no_role_in_app: 've_no_role_in_app',
    no_pending_review: 've_no_pending_review',
    exceeded: 've_exceeded',
    service_unavailable: 've_service_unavailable',
    not_approved: 've_not_approved',
    unavailable: 've_unavailable',
    operation_not_permitted: 've_operation_not_permitted',
    already_verified: 've_already_verified',
    do_not_match_invite_user: 've_do_not_match_invite_user',
    app_key_invalid: 've_app_key_invalid',
    auth_invalid: 've_auth_invalid',
    app_key_forbidden: 've_app_key_forbidden',
    auth_forbidden: 've_auth_forbidden',
    already_exists_in_another_mr: 've_already_exists_in_another_mr',
};

export const CODEMESSAGE: any = {
    200: 'code_ok',
    201: 'code_created',
    400: 'code_bad_request',
    401: 'code_unauthorized',
    403: 'code_forbidden',
    404: 'code_not_found',
    406: 'code_not_acceptable',
    409: 'code_conflict',
    422: 'code_unprocessable_entity',
    429: 'code_too_many_requests',
    500: 'code_internal_server_error',
};
